name: TIA Project Manager Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: TIA-Project-Manager.sln
      Project_Path: Interface\Interface.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Build the solution
    - name: Build the solution
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    # Publish the WPF application
    - name: Publish the application
      run: dotnet publish $env:Project_Path --configuration ${{ matrix.configuration }} --output ./publish

    # Create a ZIP archive of the published files
    - name: Create ZIP archive
      run: Compress-Archive -Path ./publish/* -DestinationPath ./TIA-Project-Manager-windows.zip

    # Create a release
    - name: Creating Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./TIA-Project-Manager-windows.zip
